<?php

namespace Davispeixoto\OpenTravelAlliance\DynamicPkgIDsType;

/**
 * Class representing DynamicPkgIDAType
 */
class DynamicPkgIDAType
{

    /**
     * Defines the type of Reservation ID (e.g. reservation number, cancellation
     * number). Refer to OpenTravel Code List Unique ID Type (UIT).
     *
     * @property string $resIDType
     */
    private $resIDType = null;

    /**
     * This is the actual value associated with ResID_Type as generated by the system
     * that is the source of the ResID_Type.
     *
     * @property string $resIDValue
     */
    private $resIDValue = null;

    /**
     * A unique identifier to indicate the source system which generated the
     * ResID_Value.
     *
     * @property string $resIDSource
     */
    private $resIDSource = null;

    /**
     * Additional information on Source.
     *
     * @property string $resIDSourceContext
     */
    private $resIDSourceContext = null;

    /**
     * Gets as resIDType
     *
     * Defines the type of Reservation ID (e.g. reservation number, cancellation
     * number). Refer to OpenTravel Code List Unique ID Type (UIT).
     *
     * @return string
     */
    public function getResIDType()
    {
        return $this->resIDType;
    }

    /**
     * Sets a new resIDType
     *
     * Defines the type of Reservation ID (e.g. reservation number, cancellation
     * number). Refer to OpenTravel Code List Unique ID Type (UIT).
     *
     * @param string $resIDType
     * @return self
     */
    public function setResIDType($resIDType)
    {
        $this->resIDType = $resIDType;

        return $this;
    }

    /**
     * Gets as resIDValue
     *
     * This is the actual value associated with ResID_Type as generated by the system
     * that is the source of the ResID_Type.
     *
     * @return string
     */
    public function getResIDValue()
    {
        return $this->resIDValue;
    }

    /**
     * Sets a new resIDValue
     *
     * This is the actual value associated with ResID_Type as generated by the system
     * that is the source of the ResID_Type.
     *
     * @param string $resIDValue
     * @return self
     */
    public function setResIDValue($resIDValue)
    {
        $this->resIDValue = $resIDValue;

        return $this;
    }

    /**
     * Gets as resIDSource
     *
     * A unique identifier to indicate the source system which generated the
     * ResID_Value.
     *
     * @return string
     */
    public function getResIDSource()
    {
        return $this->resIDSource;
    }

    /**
     * Sets a new resIDSource
     *
     * A unique identifier to indicate the source system which generated the
     * ResID_Value.
     *
     * @param string $resIDSource
     * @return self
     */
    public function setResIDSource($resIDSource)
    {
        $this->resIDSource = $resIDSource;

        return $this;
    }

    /**
     * Gets as resIDSourceContext
     *
     * Additional information on Source.
     *
     * @return string
     */
    public function getResIDSourceContext()
    {
        return $this->resIDSourceContext;
    }

    /**
     * Sets a new resIDSourceContext
     *
     * Additional information on Source.
     *
     * @param string $resIDSourceContext
     * @return self
     */
    public function setResIDSourceContext($resIDSourceContext)
    {
        $this->resIDSourceContext = $resIDSourceContext;

        return $this;
    }


}

