<?php

namespace Davispeixoto\OpenTravelAlliance\OTAHotelResRS\HotelReservationsAType\HotelReservationAType\ResGlobalInfoAType\HotelReservationIDsAType;

/**
 * Class representing HotelReservationIDAType
 */
class HotelReservationIDAType
{

    /**
     * ResID_Type MUST specify the type of Reservation ID (e.g. reservation number,
     * cancellation number). ResID_Type MUST refer to OpenTravel Code List Unique ID
     * Type (UIT). FastRez RECOMMENDS restricting the use of the code table to code 14
     * - Reservation.
     *
     * @property string $resIDType
     */
    private $resIDType = null;

    /**
     * The ResID_Value MUST specify the actual value associated with ResID_Type as
     * generated by the system that is the source of the ResID_Type.
     *
     * @property string $resIDValue
     */
    private $resIDValue = null;

    /**
     * ResID_Source MUST specify a unique identifier to indicate the source system
     * which generated the ResID_Value.
     *
     * @property string $resIDSource
     */
    private $resIDSource = null;

    /**
     * ResID_SourceContext MUST specify the context of the source.
     *
     * @property string $resIDSourceContext
     */
    private $resIDSourceContext = null;

    /**
     * Gets as resIDType
     *
     * ResID_Type MUST specify the type of Reservation ID (e.g. reservation number,
     * cancellation number). ResID_Type MUST refer to OpenTravel Code List Unique ID
     * Type (UIT). FastRez RECOMMENDS restricting the use of the code table to code 14
     * - Reservation.
     *
     * @return string
     */
    public function getResIDType()
    {
        return $this->resIDType;
    }

    /**
     * Sets a new resIDType
     *
     * ResID_Type MUST specify the type of Reservation ID (e.g. reservation number,
     * cancellation number). ResID_Type MUST refer to OpenTravel Code List Unique ID
     * Type (UIT). FastRez RECOMMENDS restricting the use of the code table to code 14
     * - Reservation.
     *
     * @param string $resIDType
     * @return self
     */
    public function setResIDType($resIDType)
    {
        $this->resIDType = $resIDType;

        return $this;
    }

    /**
     * Gets as resIDValue
     *
     * The ResID_Value MUST specify the actual value associated with ResID_Type as
     * generated by the system that is the source of the ResID_Type.
     *
     * @return string
     */
    public function getResIDValue()
    {
        return $this->resIDValue;
    }

    /**
     * Sets a new resIDValue
     *
     * The ResID_Value MUST specify the actual value associated with ResID_Type as
     * generated by the system that is the source of the ResID_Type.
     *
     * @param string $resIDValue
     * @return self
     */
    public function setResIDValue($resIDValue)
    {
        $this->resIDValue = $resIDValue;

        return $this;
    }

    /**
     * Gets as resIDSource
     *
     * ResID_Source MUST specify a unique identifier to indicate the source system
     * which generated the ResID_Value.
     *
     * @return string
     */
    public function getResIDSource()
    {
        return $this->resIDSource;
    }

    /**
     * Sets a new resIDSource
     *
     * ResID_Source MUST specify a unique identifier to indicate the source system
     * which generated the ResID_Value.
     *
     * @param string $resIDSource
     * @return self
     */
    public function setResIDSource($resIDSource)
    {
        $this->resIDSource = $resIDSource;

        return $this;
    }

    /**
     * Gets as resIDSourceContext
     *
     * ResID_SourceContext MUST specify the context of the source.
     *
     * @return string
     */
    public function getResIDSourceContext()
    {
        return $this->resIDSourceContext;
    }

    /**
     * Sets a new resIDSourceContext
     *
     * ResID_SourceContext MUST specify the context of the source.
     *
     * @param string $resIDSourceContext
     * @return self
     */
    public function setResIDSourceContext($resIDSourceContext)
    {
        $this->resIDSourceContext = $resIDSourceContext;

        return $this;
    }


}

